site_name: Thailand Competitive Programming Wiki
site_url: https://thai-cp.github.io/

nav:
  - Home: index.md
  - ทั่วไป:
    - อะไรคือ Competitive Programming?: general/intro-cp.md
    - สอวน. คอมพิวเตอร์: general/posn.md
    - แหล่งเรียนรู้: general/resources.md
  - การเขียนโปรแกรมเบื้องต้น:
    - บทนำ: prog-basic/index.md
    - วิธีการรันโปรแกรม: prog-basic/run-code.md
    - การเขียนโปรแกรมภาษา C:
      - Hello, World!: prog-basic/c/hello-world.md
      - ตัวแปร ชนิดข้อมูล และตัวดำเนินการ: prog-basic/c/variable.md
      - การส่งออกและนำเข้าข้อมูล: prog-basic/c/input-output.md
      - คำสั่ง if - else: prog-basic/c/if-else.md
  - โครงสร้างข้อมูลและอัลกอริทึ่ม:
    - อัลกอรึที่ม:
      - binary search: algorithm/binary-search.md
    # - การเขียนโปรแกรมภาษา C++:
    #   -
  - โจทย์: problems/index.md

theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to Dark Mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to Light Mode
  features:
    - navigation.tabs
    - navigation.instant
    

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - extensions.problem_tag:
      problems_dir: docs/problems/
  - extensions.problem_info:
      problems_dir: docs/problems/
  - extensions.problem_all:
      problems_dir: docs/problems/
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra:
  analytics:
    provider: google
    property: G-X3SVQVTEE3