site_name: Thailand Competitive Programming Wiki
site_url: https://thai-cp.github.io/

nav:
  - ทั่วไป:
    - Thailand Competitive Programming Wiki: index.md
    - อะไรคือ Competitive Programming?: general/intro-cp.md
    - สอวน. คอมพิวเตอร์: general/posn.md
    - แหล่งเรียนรู้: general/resources.md
  - การเขียนโปรแกรมเบื้องต้น:
    - บทนำ: prog-basic/index.md
    - วิธีการรันโปรแกรม: prog-basic/run-code.md
    - การเขียนโปรแกรมภาษา C:
      - Hello, World!: prog-basic/c/hello-world.md
      - ตัวแปร ชนิดข้อมูล และตัวดำเนินการ: prog-basic/c/variable.md
      - การส่งออกและนำเข้าข้อมูล: prog-basic/c/input-output.md
    # - การเขียนโปรแกรมภาษา C++:
    #   -

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to Dark Mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to Light Mode
  features:
    - navigation.tabs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - extensions.problem_tag:

      problems_dir: docs/problems/

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js